markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: weiqifa
author: "weiqifa"
email: 329410527@qq.com
name: "weiqifa's Blog"
baseurl: /
url: https://github.com/weiqifa0/weiqifa1.github.io
domain: https://github.com/weiqifa0/weiqifa1.github.io

all_categories: [
  ["android", "Android开发","/android/index.html"], 
  ["react", "C/C++", "/react/index.html"],
  ["web", "Linux","/web/index.html"], 
  ["linux", "Linux相关","/linux/index.html"],
  ["git", "git用法","/git/index.html"],
  ["program", "软件开发","/program/index.html"],
  ["vps", "嵌入式","/vps/index.html"],
  ["other", "蓝牙/BLE","/other/index.html"],
  ["read", "书摘","/read/index.html"], 
  ["about", "关于我","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
